// Auto-generated by train_models.py - do not edit manually.
const MODEL_DATA = {
  "feature_names": [
    "Age",
    "Tenure_Months",
    "Visits_Last_Year",
    "Missed_Appointments",
    "Days_Since_Last_Visit",
    "Overall_Satisfaction",
    "Wait_Time_Satisfaction",
    "Staff_Satisfaction",
    "Provider_Rating",
    "Avg_Out_Of_Pocket_Cost",
    "Billing_Issues",
    "Portal_Usage",
    "Referrals_Made",
    "Distance_To_Facility_Miles",
    "Age_Tenure",
    "Days_per_Tenure",
    "Cost_Tenure",
    "Missed_Ratio",
    "Visit_Per_Month",
    "Log_Cost",
    "Cost_Per_Visit",
    "High_Cost_Low_Sat",
    "Log_Days",
    "Sqrt_Days",
    "Long_Absent",
    "Very_Long_Absent",
    "Engagement_Score",
    "Billing_Dissatisfaction",
    "Billing_And_Poor_Wait",
    "Distance_Missed",
    "Access_Score",
    "Provider_Overall_Dissatisfaction",
    "Sat_Times_Portal",
    "Recency_Missed",
    "Sat_Tenure",
    "Cost_Sat",
    "Visits_Sat",
    "Total_Satisfaction",
    "Avg_Satisfaction",
    "Min_Satisfaction",
    "Sat_Variance",
    "Gender_Male",
    "State_CA",
    "State_FL",
    "State_GA",
    "State_IL",
    "State_MI",
    "State_NC",
    "State_NY",
    "State_OH",
    "State_PA",
    "State_TX",
    "Specialty_Cardiology",
    "Specialty_Family Medicine",
    "Specialty_General Practice",
    "Specialty_Internal Medicine",
    "Specialty_Neurology",
    "Specialty_Orthopedics",
    "Specialty_Pediatrics",
    "Insurance_Type_Medicaid",
    "Insurance_Type_Medicare",
    "Insurance_Type_Private",
    "Insurance_Type_Self-Pay",
    "Private_SelfPay_Cost"
  ],
  "binary_cols": [
    "Billing_Issues",
    "Portal_Usage",
    "Gender_Male",
    "Long_Absent",
    "Very_Long_Absent",
    "State_CA",
    "State_FL",
    "State_GA",
    "State_IL",
    "State_MI",
    "State_NC",
    "State_NY",
    "State_OH",
    "State_PA",
    "State_TX",
    "Specialty_Cardiology",
    "Specialty_Family Medicine",
    "Specialty_General Practice",
    "Specialty_Internal Medicine",
    "Specialty_Neurology",
    "Specialty_Orthopedics",
    "Specialty_Pediatrics",
    "Insurance_Type_Medicaid",
    "Insurance_Type_Medicare",
    "Insurance_Type_Private",
    "Insurance_Type_Self-Pay"
  ],
  "numeric_cols": [
    "PatientID",
    "Age",
    "Tenure_Months",
    "Visits_Last_Year",
    "Missed_Appointments",
    "Days_Since_Last_Visit",
    "Last_Interaction_Date",
    "Overall_Satisfaction",
    "Wait_Time_Satisfaction",
    "Staff_Satisfaction",
    "Provider_Rating",
    "Avg_Out_Of_Pocket_Cost",
    "Referrals_Made",
    "Distance_To_Facility_Miles",
    "Churned",
    "Age_Tenure",
    "Days_per_Tenure",
    "Cost_Tenure",
    "Missed_Ratio",
    "Visit_Per_Month",
    "Log_Cost",
    "Cost_Per_Visit",
    "High_Cost_Low_Sat",
    "Log_Days",
    "Sqrt_Days",
    "Engagement_Score",
    "Billing_Dissatisfaction",
    "Billing_And_Poor_Wait",
    "Distance_Missed",
    "Access_Score",
    "Provider_Overall_Dissatisfaction",
    "Sat_Times_Portal",
    "Recency_Missed",
    "Sat_Tenure",
    "Cost_Sat",
    "Visits_Sat",
    "Total_Satisfaction",
    "Avg_Satisfaction",
    "Min_Satisfaction",
    "Sat_Variance",
    "Private_SelfPay_Cost"
  ],
  "categorical_source": {
    "State": [
      "CA",
      "FL",
      "GA",
      "IL",
      "MI",
      "NC",
      "NY",
      "OH",
      "PA",
      "TX"
    ],
    "Specialty": [
      "Cardiology",
      "Family Medicine",
      "General Practice",
      "Internal Medicine",
      "Neurology",
      "Orthopedics",
      "Pediatrics"
    ],
    "Insurance_Type": [
      "Medicaid",
      "Medicare",
      "Private",
      "Self-Pay"
    ]
  },
  "scaler_params": {
    "Age": {
      "mean": 52.9725,
      "std": 15.84962124941792
    },
    "Tenure_Months": {
      "mean": 60.24625,
      "std": 35.42501744442054
    },
    "Visits_Last_Year": {
      "mean": 7.635625,
      "std": 4.657693190773199
    },
    "Missed_Appointments": {
      "mean": 2.02875,
      "std": 1.6960758937913105
    },
    "Days_Since_Last_Visit": {
      "mean": 365.29375,
      "std": 211.43122099382043
    },
    "Overall_Satisfaction": {
      "mean": 3.255875000000005,
      "std": 1.0031652328380367
    },
    "Wait_Time_Satisfaction": {
      "mean": 3.296062499999997,
      "std": 1.0040807965964431
    },
    "Staff_Satisfaction": {
      "mean": 3.5296874999999965,
      "std": 0.8652166794183702
    },
    "Provider_Rating": {
      "mean": 3.734562499999997,
      "std": 0.7306840518266117
    },
    "Avg_Out_Of_Pocket_Cost": {
      "mean": 838.22,
      "std": 587.9537250923748
    },
    "Referrals_Made": {
      "mean": 1.4725,
      "std": 1.0945290082953487
    },
    "Distance_To_Facility_Miles": {
      "mean": 24.877812499999944,
      "std": 13.878779267819048
    },
    "Age_Tenure": {
      "mean": 3203.895,
      "std": 2198.7228642953173
    },
    "Days_per_Tenure": {
      "mean": 14.214368852615912,
      "std": 29.82060164783994
    },
    "Cost_Tenure": {
      "mean": 30.559985842784055,
      "std": 68.02483626664959
    },
    "Missed_Ratio": {
      "mean": 0.2559806842463089,
      "std": 0.22802421472043433
    },
    "Visit_Per_Month": {
      "mean": 1.8291196663451261,
      "std": 1.9302766836756318
    },
    "Log_Cost": {
      "mean": 6.370733398330523,
      "std": 0.9762095204984801
    },
    "Cost_Per_Visit": {
      "mean": 177.69277366296905,
      "std": 273.77438826627855
    },
    "High_Cost_Low_Sat": {
      "mean": 1418.7159999999983,
      "std": 1371.580490545121
    },
    "Log_Days": {
      "mean": 5.61034870620786,
      "std": 0.9493161006372504
    },
    "Sqrt_Days": {
      "mean": 18.029422957713827,
      "std": 6.343000694613024
    },
    "Engagement_Score": {
      "mean": 5.914375,
      "std": 4.435740452210331
    },
    "Billing_Dissatisfaction": {
      "mean": 0.12443749999999998,
      "std": 0.5230167861491105
    },
    "Billing_And_Poor_Wait": {
      "mean": 0.12312499999999998,
      "std": 0.515123999028392
    },
    "Distance_Missed": {
      "mean": 51.301562499999946,
      "std": 57.60149220123185
    },
    "Access_Score": {
      "mean": 68.3562500000001,
      "std": 62.17539627185741
    },
    "Provider_Overall_Dissatisfaction": {
      "mean": 2.2238875000000013,
      "std": 1.9794645771884243
    },
    "Sat_Times_Portal": {
      "mean": 0.6646250000000004,
      "std": 1.3973049450191464
    },
    "Recency_Missed": {
      "mean": 741.09875,
      "std": 824.0812461453273
    },
    "Sat_Tenure": {
      "mean": 196.31275000000005,
      "std": 134.75061790187635
    },
    "Cost_Sat": {
      "mean": 2772.384,
      "std": 2255.7184586610083
    },
    "Visits_Sat": {
      "mean": 24.868437500000038,
      "std": 17.513399086373656
    },
    "Total_Satisfaction": {
      "mean": 13.816187500000012,
      "std": 1.8176032886314184
    },
    "Avg_Satisfaction": {
      "mean": 3.454046875000003,
      "std": 0.4544008221578546
    },
    "Min_Satisfaction": {
      "mean": 2.4593124999999914,
      "std": 0.600042312961137
    },
    "Sat_Variance": {
      "mean": 0.8732463541666678,
      "std": 0.5676814800871441
    },
    "Private_SelfPay_Cost": {
      "mean": 516.581875,
      "std": 649.1307328238914
    }
  },
  "logistic_regression": {
    "metrics": {
      "accuracy": 0.6675,
      "precision": 0.6955307262569832,
      "recall": 0.9120879120879121,
      "f1": 0.7892234548335975,
      "auc": 0.6109140203628394,
      "cm": [
        [
          18,
          109
        ],
        [
          24,
          249
        ]
      ],
      "threshold": 0.5300000000000002,
      "roc_curve": {
        "fpr": [
          0.0,
          0.047244094488188976,
          0.09448818897637795,
          0.14173228346456693,
          0.1732283464566929,
          0.2125984251968504,
          0.2440944881889764,
          0.31496062992125984,
          0.3543307086614173,
          0.4015748031496063,
          0.4330708661417323,
          0.48031496062992124,
          0.5590551181102362,
          0.5984251968503937,
          0.6299212598425197,
          0.6692913385826772,
          0.7874015748031497,
          0.8346456692913385,
          0.8740157480314961,
          0.9133858267716536,
          1.0
        ],
        "tpr": [
          0.0,
          0.11355311355311355,
          0.16483516483516483,
          0.23443223443223443,
          0.3076923076923077,
          0.38095238095238093,
          0.42124542124542125,
          0.4835164835164835,
          0.5238095238095238,
          0.5641025641025641,
          0.63003663003663,
          0.6483516483516484,
          0.6996336996336996,
          0.7216117216117216,
          0.7619047619047619,
          0.7912087912087912,
          0.8388278388278388,
          0.8791208791208791,
          0.9157509157509157,
          0.9743589743589743,
          1.0
        ]
      }
    },
    "model": {
      "intercept": 0.7557191537371899,
      "coefficients": {
        "Age": -0.0649267550317044,
        "Tenure_Months": 0.0,
        "Visits_Last_Year": 0.0,
        "Missed_Appointments": 0.0,
        "Days_Since_Last_Visit": 0.0,
        "Overall_Satisfaction": -0.15914192706268807,
        "Wait_Time_Satisfaction": -0.07384968695780586,
        "Staff_Satisfaction": 0.0,
        "Provider_Rating": 0.0,
        "Avg_Out_Of_Pocket_Cost": 0.1051292492861193,
        "Billing_Issues": 0.0,
        "Portal_Usage": 0.0,
        "Referrals_Made": -0.05557420622081117,
        "Distance_To_Facility_Miles": 0.05393634429311896,
        "Age_Tenure": 0.0,
        "Days_per_Tenure": 0.028296845591021646,
        "Cost_Tenure": 0.0,
        "Missed_Ratio": 0.0,
        "Visit_Per_Month": 0.0,
        "Log_Cost": 0.0,
        "Cost_Per_Visit": 0.0,
        "High_Cost_Low_Sat": 0.0,
        "Log_Days": 0.0,
        "Sqrt_Days": 0.0,
        "Long_Absent": 0.10107603648660803,
        "Very_Long_Absent": 0.0,
        "Engagement_Score": 0.0,
        "Billing_Dissatisfaction": 0.0,
        "Billing_And_Poor_Wait": 0.08546527634250202,
        "Distance_Missed": 0.0,
        "Access_Score": 0.10173805081219986,
        "Provider_Overall_Dissatisfaction": 0.14759701214387458,
        "Sat_Times_Portal": -0.059080408912762096,
        "Recency_Missed": 0.1448672960240022,
        "Sat_Tenure": -0.1073236740136148,
        "Cost_Sat": 0.0,
        "Visits_Sat": 0.0,
        "Total_Satisfaction": 0.0,
        "Avg_Satisfaction": 0.0,
        "Min_Satisfaction": 0.0,
        "Sat_Variance": 0.0,
        "Gender_Male": 0.0,
        "State_CA": -0.004203735874227853,
        "State_FL": 0.0,
        "State_GA": 0.0,
        "State_IL": 0.0,
        "State_MI": 0.0,
        "State_NC": 0.0,
        "State_NY": 0.0,
        "State_OH": 0.0,
        "State_PA": 0.0,
        "State_TX": 0.0,
        "Specialty_Cardiology": 0.0,
        "Specialty_Family Medicine": 0.0,
        "Specialty_General Practice": 0.0,
        "Specialty_Internal Medicine": 0.0,
        "Specialty_Neurology": 0.0,
        "Specialty_Orthopedics": -0.00038225224365529253,
        "Specialty_Pediatrics": 0.0,
        "Insurance_Type_Medicaid": 0.0,
        "Insurance_Type_Medicare": 0.0,
        "Insurance_Type_Private": 0.0,
        "Insurance_Type_Self-Pay": -0.010563525084678326,
        "Private_SelfPay_Cost": 0.0
      }
    }
  },
  "decision_tree": {
    "metrics": {
      "accuracy": 0.6825,
      "precision": 0.6825,
      "recall": 1.0,
      "f1": 0.8112927191679049,
      "auc": 0.5701018141963023,
      "cm": [
        [
          0,
          127
        ],
        [
          0,
          273
        ]
      ],
      "threshold": 0.2,
      "roc_curve": {
        "fpr": [
          0.0,
          0.023622047244094488,
          0.06299212598425197,
          0.16535433070866143,
          0.3700787401574803,
          0.6692913385826772,
          1.0
        ],
        "tpr": [
          0.0,
          0.047619047619047616,
          0.12087912087912088,
          0.26373626373626374,
          0.45787545787545786,
          0.7582417582417582,
          1.0
        ]
      }
    },
    "nodes": [
      {
        "id": 0,
        "is_leaf": false,
        "left_child": 1,
        "right_child": 8,
        "feature": "Provider_Overall_Dissatisfaction",
        "threshold": 0.952839732170105,
        "churn_probability": 0.68375,
        "samples": 1
      },
      {
        "id": 1,
        "is_leaf": false,
        "left_child": 2,
        "right_child": 5,
        "feature": "Days_per_Tenure",
        "threshold": -0.16335122287273407,
        "churn_probability": 0.6500765696784073,
        "samples": 1
      },
      {
        "id": 2,
        "is_leaf": false,
        "left_child": 3,
        "right_child": 4,
        "feature": "Access_Score",
        "threshold": -0.41264311969280243,
        "churn_probability": 0.6058890147225368,
        "samples": 1
      },
      {
        "id": 3,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 0.52,
        "samples": 1
      },
      {
        "id": 4,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 0.6855895196506551,
        "samples": 1
      },
      {
        "id": 5,
        "is_leaf": false,
        "left_child": 6,
        "right_child": 7,
        "feature": "Referrals_Made",
        "threshold": -0.8885100185871124,
        "churn_probability": 0.7423167848699763,
        "samples": 1
      },
      {
        "id": 6,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 0.8737864077669902,
        "samples": 1
      },
      {
        "id": 7,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 0.7,
        "samples": 1
      },
      {
        "id": 8,
        "is_leaf": false,
        "left_child": 9,
        "right_child": 12,
        "feature": "Recency_Missed",
        "threshold": 1.5561587810516357,
        "churn_probability": 0.8333333333333334,
        "samples": 1
      },
      {
        "id": 9,
        "is_leaf": false,
        "left_child": 10,
        "right_child": 11,
        "feature": "Days_Since_Last_Visit",
        "threshold": -1.2925893664360046,
        "churn_probability": 0.810077519379845,
        "samples": 1
      },
      {
        "id": 10,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 1.0,
        "samples": 1
      },
      {
        "id": 11,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 0.7841409691629956,
        "samples": 1
      },
      {
        "id": 12,
        "is_leaf": true,
        "left_child": -1,
        "right_child": -1,
        "feature": null,
        "threshold": -2.0,
        "churn_probability": 1.0,
        "samples": 1
      }
    ],
    "importances": {
      "Age": 0.0,
      "Tenure_Months": 0.0,
      "Visits_Last_Year": 0.0,
      "Missed_Appointments": 0.0,
      "Days_Since_Last_Visit": 0.10605684249766037,
      "Overall_Satisfaction": 0.0,
      "Wait_Time_Satisfaction": 0.0,
      "Staff_Satisfaction": 0.0,
      "Provider_Rating": 0.0,
      "Avg_Out_Of_Pocket_Cost": 0.0,
      "Billing_Issues": 0.0,
      "Portal_Usage": 0.0,
      "Referrals_Made": 0.10357746290670175,
      "Distance_To_Facility_Miles": 0.0,
      "Age_Tenure": 0.0,
      "Days_per_Tenure": 0.18208338493115125,
      "Cost_Tenure": 0.0,
      "Missed_Ratio": 0.0,
      "Visit_Per_Month": 0.0,
      "Log_Cost": 0.0,
      "Cost_Per_Visit": 0.0,
      "High_Cost_Low_Sat": 0.0,
      "Log_Days": 0.0,
      "Sqrt_Days": 0.0,
      "Long_Absent": 0.0,
      "Very_Long_Absent": 0.0,
      "Engagement_Score": 0.0,
      "Billing_Dissatisfaction": 0.0,
      "Billing_And_Poor_Wait": 0.0,
      "Distance_Missed": 0.0,
      "Access_Score": 0.1922456960806409,
      "Provider_Overall_Dissatisfaction": 0.3093905408897822,
      "Sat_Times_Portal": 0.0,
      "Recency_Missed": 0.10664607269406337,
      "Sat_Tenure": 0.0,
      "Cost_Sat": 0.0,
      "Visits_Sat": 0.0,
      "Total_Satisfaction": 0.0,
      "Avg_Satisfaction": 0.0,
      "Min_Satisfaction": 0.0,
      "Sat_Variance": 0.0,
      "Gender_Male": 0.0,
      "State_CA": 0.0,
      "State_FL": 0.0,
      "State_GA": 0.0,
      "State_IL": 0.0,
      "State_MI": 0.0,
      "State_NC": 0.0,
      "State_NY": 0.0,
      "State_OH": 0.0,
      "State_PA": 0.0,
      "State_TX": 0.0,
      "Specialty_Cardiology": 0.0,
      "Specialty_Family Medicine": 0.0,
      "Specialty_General Practice": 0.0,
      "Specialty_Internal Medicine": 0.0,
      "Specialty_Neurology": 0.0,
      "Specialty_Orthopedics": 0.0,
      "Specialty_Pediatrics": 0.0,
      "Insurance_Type_Medicaid": 0.0,
      "Insurance_Type_Medicare": 0.0,
      "Insurance_Type_Private": 0.0,
      "Insurance_Type_Self-Pay": 0.0,
      "Private_SelfPay_Cost": 0.0
    }
  },
  "adaboost": {
    "metrics": {
      "accuracy": 0.6725,
      "precision": 0.695054945054945,
      "recall": 0.9267399267399268,
      "f1": 0.7943485086342229,
      "auc": 0.6010787113149318,
      "cm": [
        [
          16,
          111
        ],
        [
          20,
          253
        ]
      ],
      "threshold": 0.5000000000000002,
      "roc_curve": {
        "fpr": [
          0.0,
          0.031496062992125984,
          0.07874015748031496,
          0.12598425196850394,
          0.14960629921259844,
          0.1889763779527559,
          0.23622047244094488,
          0.28346456692913385,
          0.33070866141732286,
          0.36220472440944884,
          0.4015748031496063,
          0.4566929133858268,
          0.5039370078740157,
          0.5433070866141733,
          0.5905511811023622,
          0.6220472440944882,
          0.6850393700787402,
          0.7401574803149606,
          0.7716535433070866,
          0.8503937007874016,
          0.889763779527559,
          0.9606299212598425
        ],
        "tpr": [
          0.0,
          0.047619047619047616,
          0.13553113553113552,
          0.1794871794871795,
          0.2564102564102564,
          0.315018315018315,
          0.37362637362637363,
          0.3992673992673993,
          0.4542124542124542,
          0.5201465201465202,
          0.5824175824175825,
          0.6043956043956044,
          0.63003663003663,
          0.673992673992674,
          0.6959706959706959,
          0.73992673992674,
          0.8021978021978022,
          0.8461538461538461,
          0.8827838827838828,
          0.9084249084249084,
          0.9523809523809523,
          0.989010989010989
        ]
      }
    },
    "importances": {
      "Age": 0.030476640868309098,
      "Tenure_Months": 0.006371375143985408,
      "Visits_Last_Year": 7.42246786465604e-17,
      "Missed_Appointments": 0.0,
      "Days_Since_Last_Visit": 0.01432483245397595,
      "Overall_Satisfaction": 0.06622056640040842,
      "Wait_Time_Satisfaction": 0.012044649540582035,
      "Staff_Satisfaction": 0.0,
      "Provider_Rating": 0.0,
      "Avg_Out_Of_Pocket_Cost": 0.01241278648858274,
      "Billing_Issues": 0.0,
      "Portal_Usage": 0.0,
      "Referrals_Made": 0.012258557633179337,
      "Distance_To_Facility_Miles": 0.003043946847705522,
      "Age_Tenure": 0.08057792351053482,
      "Days_per_Tenure": 0.02156231021697412,
      "Cost_Tenure": 0.004187585252510758,
      "Missed_Ratio": 1.4069391780852188e-16,
      "Visit_Per_Month": 0.017772973480489312,
      "Log_Cost": 0.012940530381691294,
      "Cost_Per_Visit": 0.02971538685475364,
      "High_Cost_Low_Sat": 0.046353946116779586,
      "Log_Days": 0.013790877252912493,
      "Sqrt_Days": 0.022206443565637893,
      "Long_Absent": 1.0584363079249343e-16,
      "Very_Long_Absent": 0.0,
      "Engagement_Score": 0.00492503278370026,
      "Billing_Dissatisfaction": 0.003045089924618362,
      "Billing_And_Poor_Wait": 0.022619760540382772,
      "Distance_Missed": 0.00722204368448666,
      "Access_Score": 0.0873108039035391,
      "Provider_Overall_Dissatisfaction": 0.08995669311034996,
      "Sat_Times_Portal": 0.01446506417579978,
      "Recency_Missed": 0.20583377478831355,
      "Sat_Tenure": 0.012397185797891631,
      "Cost_Sat": 0.03783468807670862,
      "Visits_Sat": 0.0012317744632854822,
      "Total_Satisfaction": 0.006390853744147958,
      "Avg_Satisfaction": 0.0043640539574093876,
      "Min_Satisfaction": 0.0,
      "Sat_Variance": 0.09165775189397295,
      "Gender_Male": 0.0,
      "State_CA": 3.703749007422667e-17,
      "State_FL": 0.0,
      "State_GA": 0.0,
      "State_IL": 0.0,
      "State_MI": 0.0,
      "State_NC": 4.430736273009966e-17,
      "State_NY": 0.0,
      "State_OH": 0.0,
      "State_PA": 0.0,
      "State_TX": 0.0,
      "Specialty_Cardiology": 0.0,
      "Specialty_Family Medicine": 0.0,
      "Specialty_General Practice": 0.0,
      "Specialty_Internal Medicine": 0.0,
      "Specialty_Neurology": 0.0,
      "Specialty_Orthopedics": 0.0,
      "Specialty_Pediatrics": 0.0,
      "Insurance_Type_Medicaid": 0.0,
      "Insurance_Type_Medicare": 0.0,
      "Insurance_Type_Private": 0.0,
      "Insurance_Type_Self-Pay": 0.0,
      "Private_SelfPay_Cost": 0.004484097146380654
    }
  }
};
